### ISSUE TITLE
This job id has no regions to process, exiting...

### ISSUE THREAD

**Issue by muppetjones** [zstephens/neat-genreads#11]
I keep getting this error, but I cannot tell if this is an issue or not. Looking at the code, the regions should be spread evenly across the threads, and if there are too many threads, it will lower the number of threads.

`This job id has no regions to process, exiting...`

I wonder--is this check working? (And does it happen before the reference is loaded in memory?)

**Comment by zstephens** [comment]
Hi there,

This is not necessarily an error, but an indicator that the number of jobs specified exceeds the number of regions the reference can be split into for processing (see my previous message about how the parallel jobs work, splitting up ref regions separated by N-regions). For example, if the reference has 50 possible isolated regions but you specify 60 job ids, the last 10 jobs will exit immediately with that message because they have no regions to process.

I’m amenable to eventually making the parallel job options more intuitive (i.e. not dependent on reference, no maximum number of jobs), but the current implementation is as it is because of how comparatively simple it was to implement.

-Zach

On Oct 17, 2016, at 11:48 AM, Stephen J Bush <notifications@github.com<mailto:notifications@github.com>> wrote:


I keep getting this error for some reason...

This job id has no regions to process, exiting...

**Comment by muppetjones** [comment]
Makes sense. I wonder if the memory errors (separate issue) are due to parsing the reference or a high coverage. If it's the reference, I think the only way to fix it would be to pause all jobs while one calculates the regions and writes them to a file, then have each job read the regions...which would be a headache.
