### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by muppetjones** [zstephens/neat-genreads#13]
In `py/vcfFunc.py`, line 88: `for line in open(vcfPath,'r'):` contains an unclosed file handle. Also, there's a mixture of using the context manager `with open(...) as fh:` and just calling open `fh = open(...)`. The latter is fine so long as the handle is closed even if any exceptions occur, but the former is better (e.g., `refFunc.py:83,160`)

Also, `OutputFileWriter` should open files as needed (just 'append') rather than keeping them open. Opening a file is a very low cost. Another option would be to add a context manager to `OutputFileWriter`, e.g., `with ofw.openVcf(...) as fh:`, so the files remain open only as long as you intend.

**Comment by zstephens** [comment]
Low-hanging fruit, fixed the potential memory leak. I usually use that syntax for file handles so it was surprising to find that.

Are there notable drawbacks to keeping the files open? My guess is that it’s better practice in the event that the code goes down an unexpected path and the files aren’t properly closed?

-Zach


On Oct 18, 2016, at 12:25 PM, Stephen J Bush <notifications@github.com<mailto:notifications@github.com>> wrote:


In py/vcfFunc.py, line 88: for line in open(vcfPath,'r'): contains an unclosed file handle. Also, there's a mixture of using the context manager with open(...) as fh: and just calling open fh = open(...). The latter is fine so long as the handle is closed even if any exceptions occur, but the former is better (e.g., refFunc.py:83,160)

Also, OutputFileWriter should open files as needed (just 'append') rather than keeping them open. Opening a file is a very low cost. Another option would be to add a context manager to OutputFileWriter, e.g., with ofw.openVcf(...) as fh:, so the files remain open only as long as you intend.

**Comment by muppetjones** [comment]
It really depends. Leaving file handles open is bad; eventually, they'll get closed, but when and ow bad it is depends on which python and OS you're using.

As to leaving file handles open during the script, the best practice is to open them as you need them. I said above that open is low cost...that's not entirely true--it can get very expensive if you're opening it every time you write a single line; however, compared with the potential cost of having multiple, unclosed handles, it's preferential.

Unless `OutputFileWriter` has a method that will clean up the file handles when it's destroyed (which you __can__ technically do, but it's a major headache), it should not open files during `__init__`. 

Due to the memory issues, the best solution would be to:
1. store the path name as an instance attribute
2. use a context manager to open the files
3. process the line, then write it out using the custom output.

```python
# Note: Parts of this may not be compatible with python2
import contextlib

class OutputFileWriter():

	def __init__(self, path):
		self.path = path

	@property
	def fh(self):
		try:
			return self._fh
		except AttributeError:
			msg = 'You must open the file first. See OutputFileWriter.open'
			raise ValueError(msg)  # or whatever exception is appropriate

    @contextlib.contextmanager
    def open(self, mode):
        """Context manager to open files."""
        try:
        	self._fh = open(self.path, mode)
            yield self._fh
        except:
            raise
        finally:
            self._fh.close()
            del self._fh
        return
    
class VcfWriter(OutputFileWriter):
    def write_vcf_line(self, line):
    	self.fh.write(line)  # will raise exception if used outside of context manager

class BamWriter(OutputFileWriter):
    ...
    
def main():

	out_vcf = VcfWriter(output_vcf_path)
	out_bam = BamWriter(output_bam_path)
	
	# admittedly, this is ugly, but better than nested 'with'?
	with \
			open(input_vcf, 'r') as in_vcf_fh, \
			out_vcf.open('w') as out_vcf_fh, \
			out_bam.open('w') as out_bam_fh:
		for line in in_vcf_fh:
			processed_line = handle_line(line)
			
			if not processed_line:
				continue  # None or just empty? keep going
			
			# Either option will do. The first is fine if the line is completely
			# processed. The second tells the user that you still have something
			# to do to the line.
			out_vcf_fh.write(processed_line)
			out_vcf.write_vcf(processed_line)
```
