### ISSUE TITLE
How to run genReads.py with multiple threads using --job? 

### ISSUE THREAD

**Issue by rdbcasillas** [zstephens/neat-genreads#2]
Hi Zachary,
Thank you for making this! Is it possible to make it clearer in the documentation about running genReads.py using multiple threads? I couldn't exactly understand what arguments are expected with the command "--job" to achieve this.

**Comment by zstephens** [comment]
Hey Vatsal,

Parallelism is (going to be) implemented in genReads is at rather coarse level. The idea was that you could launch multiple jobs (e.g. on a cluster) and then merge the results afterward. This is a carryover feature from an earlier version that hasn’t been fully reimplemented yet, but thanks for reminding me! I’ll try and push an update either tonight or tomorrow.

In the previous version, running multiple jobs was done by (omitting various input options):

python genReads.py -o out_prefix --job 1 4         (job 1 of 4)
python genReads.py -o out_prefix --job 2 4         (job 2 of 4)
python genReads.py -o out_prefix --job 3 4         (job 3 of 4)
python genReads.py -o out_prefix --job 4 4         (job 4 of 4)

then the jobs were merged into a single .fq and .sam output via:

python mergeJobs.py out_prefix

As I mentioned, I need to reincorporate this feature, so it can’t be used right now. The syntax might be slightly different, but the idea is the same. I’ll send you a message with an example usage after I push the update.

I’ll also push some quality-of-life changes (e.g. printing % progress instead of annoying messages, etc), the software is currently transitioning from research-grade to being more user-friendly, thanks for your patience!

- Zach



if you wanted to run 4 jobs: python genReads.py

On May 24, 2016, at 3:56 PM, vatsal mehra <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Zachary,
Thank you for making this! Is it possible to make it clearer in the documentation about running genReads.py using multiple threads? I couldn't exactly understand what arguments are expected with the command "--job" to achieve this.

**Comment by zstephens** [comment]
Hey Vatsal,

Parallelization is now fully supported. I updated the documentation with some example commands.
