### ISSUE TITLE
Generating paired tumor/normal sequence 

### ISSUE THREAD

**Issue by phoebee-h** [zstephens/neat-genreads#25]
Hi 
Thanks to all the authors for such a well-designed tool!
I'm a novice in the Bioinformatics field. I want to generate paired tumor/normal sequence for testing variant callers but I have no idea what parameters should be set.
Also, based on the default Mutation Models, would it be possible to do this?

**Comment by zstephens** [comment]
Greetings!

As a starting point, check out models/genReadsTumorTutorial.zip. It includes a shell script that creates a tumor/normal dataset on a toy reference sequence. Typically, generating such datasets with our simulator follow this structure:

1) If desired, learn models for tumor/normal mutation distributions from user-provided data
—— Note that the example script learns a “tumor” mutation model from a provided file, and uses the default mutation model for “normal” variants.

2) Run genReads.py twice, once with the coverage value and mutation model for the normal portion of the data. And again for the tumor data.

3) Merge the genReads outputs into a single set of FASTQ files, for use as input to your pipelines.


Hope this helps!
- Zach


On Jul 28, 2017, at 12:50 PM, phoebee-h <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi
Thanks to all the authors for such a well-designed tool!
I'm a novice in the Bioinformatics field. I want to generate paired tumor/normal sequence for testing variant callers but I have no idea what parameters should be set.
Also, based on the default Mutation Models, would it be possible to do this?

**Comment by phoebee-h** [comment]
Thank you so much for the prompt reply!

I'd also like to ask:
Why is the read length in the "Usage" description different from the command line? Is it a typo or a tricky thing I should have to be cautious dealing with?
For example, I want to set read length with 150 bps, but in the command line -R should be 151? 
![image](https://user-images.githubusercontent.com/28743573/28747722-1dc484cc-74d8-11e7-8e48-d34a863ea1e8.png)

**Comment by phoebee-h** [comment]
Hi Zach,
Thank you so much.
I followed the instruction written in the simulated.sh, and I successfully generated tumor/normal reads based on the files you provided (chr1 subset and its model). 

After that,  I had these file done in a variant caller and then I used your VCF comparison tools 
 "vcf_compare_OLD.py" as for checking how well the variant caller performs.
In this final step, I put both "golden_normal.vcf" and "golden_tumor.vcf" separately for the "answer" (not so sure which one should be put in the case), and I got weird results like this: 

![vcf_compare](https://user-images.githubusercontent.com/28743573/29310373-18cd2734-81e0-11e7-9cd2-4ec79c03d3d9.jpg)





I wondered if I made all these things wrong:
1. While checking the answer for normal/tumor paired NEAT simulated sequence, which golden.vcf should be included in "vcf_compare_OLD.py"?
2. Or there's no reason for comparing this case? Because "vcf_compare_OLD.py" is not made for normal/tumor paired NEAT simulated sequence?

Thank you!

**Comment by phoebee-h** [comment]
Hi Zach,

Everything works well when generating the normal/tumor paired data. NEAT really is a user-friendly software! 

![image](https://user-images.githubusercontent.com/28743573/30574783-ee16bf68-9d2e-11e7-858b-20588ee3777d.png)

I'm curious about the parameter setting in the given example:
1. Does the "--pe 300 30, Paired-end fragment length mean (300) and standard deviation (30) setting" be based on any reference? 
2. "-c 80" and "-c 20" means the coverage. Why using this number? Because you want to merge both normal and tumor sequence together to be 100x?
3. In the genReadsTumorTutorial, there is a file called "mutations_tumor.vcf". I wonder how this file was produced?

Thank you.

**Comment by zstephens** [comment]
Greetings!

  1.  Does the "--pe 300 30, Paired-end fragment length mean (300) and standard deviation (30) setting" be based on any reference?

This default was chosen based on some datasets that we had sequenced in-house here. There’s nothing particularly special about it, so if you estimate these values from your own sequencing data that you wish to mimic feel free to use whatever values you wish.

  1.  "-c 80" and "-c 20" means the coverage. Why using this number? Because you want to merge both normal and tumor sequence together to be 100x?

This was just an example, simulating tumor/normal data where we picked 20% as the fraction of cancerous cells to simulate. Indeed when combined they would yield a dataset of 100x coverage.

  1.  In the genReadsTumorTutorial, there is a file called "mutations_tumor.vcf". I wonder how this file was produced?

This data was generated by running genReads previously and outputting a --vcf. It just served as some example mutations that would be tumor specific for the simulated tumor/normal dataset. I don’t recall exactly, but it may have been produced with one of the mutation models present in the models/ directory.

Spurred by this comment, I decided to clean up the models/ directory and added a readme file to make it easier to understand how they’re used: https://github.com/zstephens/neat-genreads/tree/master/models

Hope this helps!
-Zach
