### ISSUE TITLE
The -t parameter doesnt seem to be working

### ISSUE THREAD

**Issue by sert23** [zstephens/neat-genreads#27]
Hey there!
I run the following line

python genReads.py -r /shared/seq/hg38.fa -R 126 -o /home/eap/simulated_reads/phenyl2 -t /home/eap/docencia/biocomp/phenylk.bed

but I get reads from the whole genome! Any help? I attach the bed file.
[phenylk.bed.txt](https://github.com/zstephens/neat-genreads/files/1311406/phenylk.bed.txt)

**Comment by zstephens** [comment]
Greetings!

By default genReads will sample 2% of your coverage outside of the targeted regions specified by the ‘-t’ parameter. You can insist that the simulator only create reads drawn from your specified region by adding “-to 0”.

Note that some of the reads may still be outside the specified coordinates (because they might span a targeted region boundary, or perhaps their mate maps into the specified region but they themselves do not).

Hope this helps,
Zach



On Sep 18, 2017, at 11:25 AM, sert23 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey there!
I run the following line

python genReads.py -r /shared/seq/hg38.fa -R 126 -o /home/eap/simulated_reads/phenyl2 -t /home/eap/docencia/biocomp/phenylk.bed

but I get reads from the whole genome! Any help? I attach the bed file.
phenylk.bed.txt<https://github.com/zstephens/neat-genreads/files/1311406/phenylk.bed.txt>

**Comment by sert23** [comment]
Thanks for the quick answer! I'm trying that now (-to 0.0). I am not sure that was the problem because I was getting huge files and my target region was only 2 kb. I'll write back with the results.

**Comment by sert23** [comment]
Okay so 2 comments after I made it work with the -to parameter.
First: if you specify a region for a given chromosome it will use that region to sample from that chromosome, but it's still sampling reads from the rest of chromosomes (although I guess discarding them). This makes the process incredibly inefficient.
Second: you can (kind of) work around it by providing a reference with just the chromosome you are interested in. Doing that, it took my computer like 2h to get the work done. A bit unreasonable considering it's a 2kb sequence and that I am using a server with large amount of RAM and several cores.

Thanks for the help!
Ernesto

**Comment by bmscicho** [comment]
As of 5b8bc84ddd3b7bd32b425cb5dd5245bf854148db (issue #34), the sampling is not performed outside of specified regions.

@sert23: I was also using a reference with a single chromosome, with additional .bed file to further limit the region used for sampling (with `-to` set to 0). The process took 1-2 hours. Now, after the fix, it completes in few minutes.
