### ISSUE TITLE
VCF file from COSMIC

### ISSUE THREAD

**Issue by palakpsheth** [zstephens/neat-genreads#3]
Hi Zachary,
Thank you for making this! Is it possible to make it clearer in the documentation about running genReads.py using a VCF? What is the exact VCF format that is expected? I am trying to a VCF from COSMIC however am getting errors presumably due to missing GT/AF fields? I did modify the parseVCF function to have "INCLUDE_FAIL = True" however am still getting errors. Any suggestions on how to mod the COSMIC VCF for compatibility would be greatly appreciated!

Example from CSOMIC VCF:

```
##fileformat=VCFv4.1
##source=COSMICv77
##reference=GRCh37
##fileDate=20160407
##comment="Missing nucleotide details indicate ambiguity during curation process"
##comment="URL stub for COSM ID field (use numeric portion of ID)='http://grch37-cancer.sanger.ac.uk/cosmic/mutation/overview?id='"
##comment="REF and ALT sequences are both forward strand
##INFO=<ID=GENE,Number=1,Type=String,Description="Gene name">
##INFO=<ID=STRAND,Number=1,Type=String,Description="Gene strand">
##INFO=<ID=CDS,Number=1,Type=String,Description="CDS annotation">
##INFO=<ID=AA,Number=1,Type=String,Description="Peptide annotation">
##INFO=<ID=CNT,Number=1,Type=Integer,Description="How many samples have this mutation">
##INFO=<ID=SNP,Number=0,Type=Flag,Description="classified as SNP">
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO
7   55242448    COSM3734669 A   G   .   .   GENE=EGFR;STRAND=+;CDS=c.2218A>G;AA=p.I740V;CNT=1
7   55242449    COSM85892   T   TTCCCGTCGCTATTAAAAT .   .   GENE=EGFR;STRAND=+;CDS=c.2219_2220ins18;AA=p.K745_E746insIPVAIK;CNT=1
7   55242449    COSM52934   T   C   .   .   GENE=EGFR;STRAND=+;CDS=c.2219T>C;AA=p.I740T;CNT=1
7   55242463    COSM18420   AAGG    A   .   .   GENE=EGFR;STRAND=+;CDS=c.2234_2236delAGG;AA=p.E746delE;CNT=2
7   55242463    COSM1190791 AAGGAATTAAGAGAAG    A   .   .   GENE=EGFR;STRAND=+;CDS=c.2234_2248del15;AA=p.K745_A750>T;CNT=4
7   55242464    COSM13549   AGGAATTAAGAGAAGCAA  AAG .   .   GENE=EGFR;STRAND=+;CDS=c.2235_2251>AG;AA=p.E746_T751>A;CNT=1
7   55242464    COSM255152  A   AAACTCCCGTCGCTATCAA .   .   GENE=EGFR;STRAND=+;CDS=c.2234_2235ins18;AA=p.K745_E746insTPVAIK;CNT=1
7   55242464    COSM13550   AGGAATTAAGAGAAG AAATTC  .   .   GENE=EGFR;STRAND=+;CDS=c.2235_2248>AATTC;AA=p.E746_A750>IP;CNT=3
7   55242464    COSM24869   AGGAATTAAGAGAAGCAAC A   .   .   GENE=EGFR;STRAND=+;CDS=c.2235_2252del18;AA=p.E746_T751delELREAT;CNT=1
7   55242464    COSM6223    AGGAATTAAGAGAAGC    A   .   .   GENE=EGFR;STRAND=+;CDS=c.2235_2249del15;AA=p.E746_A750delELREA;CNT=1039
7   55242464    COSM51504   A   AAATTCCCGTCGCTATCAA .   .   GENE=EGFR;STRAND=+;CDS=c.2234_2235ins18;AA=p.K745_E746insIPVAIK;CNT=6
```

Regards,
Palak Sheth

**Comment by zstephens** [comment]
Hey Palak,

When I used the example vcf you provided I found that genReads was ignoring the variants because it could not find a genotype field (GT field). Currently the simulator requires that input variants have a specified genotype so that it knows which ploid to insert them into. If this information is unavailable for the variants you wish to insert, I would be amenable to coding in a default behavior of some sort. Would it make sense, for example, to have genReads assume the variant is heterozygous and randomly select an allele to insert it (i.e. randomly choose from either GT=0/1 or GT=1/0, assuming ploidy=2) if it doesn’t find a GT field?

Attached below is the console output that confirms the variants were being skipped (but otherwise ran without error, for me).

$ python genReads.py -r hs37d5.fa -R 100 -v /Users/zach/Desktop/palak_example.vcf -c 1.0 -o palak_test
Using default sequencing error model.
Warning: Read length of error model (101) does not match -R value (100), rescaling model...
Using default gc-bias model.
found index hs37d5.fa.fai
--------------------------------
reading input VCF...
found 0 valid variants in input vcf.
11 variants skipped (quality filtered, reference genotypes, or invalid syntax).
--------------------------------
reading 1...

Thanks,
Zach


On Jun 14, 2016, at 3:34 PM, palakpsheth <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Zachary,
Thank you for making this! Is it possible to make it clearer in the documentation about running genReads.py using a VCF? What is the exact VCF format that is expected? I am trying to a VCF from COSMIC however am getting errors presumably due to missing GT/AF fields? I did modify the parseVCF function to have "INCLUDE_FAIL = True" however am still getting errors. Any suggestions on how to mod the COSMIC VCF for compatibility would be greatly appreciated!

Example from CSOMIC VCF:

##fileformat=VCFv4.1
##source=COSMICv77
##reference=GRCh37
##fileDate=20160407
##comment="Missing nucleotide details indicate ambiguity during curation process"
##comment="URL stub for COSM ID field (use numeric portion of ID)='http://grch37-cancer.sanger.ac.uk/cosmic/mutation/overview?id=<https://urldefense.proofpoint.com/v2/url?u=http-3A__grch37-2Dcancer.sanger.ac.uk_cosmic_mutation_overview-3Fid-3D&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=iSEBNMfCHfS5bLIS7AqI6wkxgRNv8-2dMwRF43ddddU&m=yobONY2wu-KDAGzyExcnA9bYogfa0eX3w4zeOQJELb8&s=81jcj_o2tVWi4MP4zE63x6dbHyzNnfZd781BcPsSgbQ&e=>'"
##comment="REF and ALT sequences are both forward strand
##INFO=
##INFO=
##INFO=
##INFO=
##INFO=
##INFO=
#CHROM POS ID REF ALT QUAL FILTER INFO
7 55242448 COSM3734669 A G . . GENE=EGFR;STRAND=+;CDS=c.2218A>G;AA=p.I740V;CNT=1
7 55242449 COSM85892 T TTCCCGTCGCTATTAAAAT . . GENE=EGFR;STRAND=+;CDS=c.2219_2220ins18;AA=p.K745_E746insIPVAIK;CNT=1
7 55242449 COSM52934 T C . . GENE=EGFR;STRAND=+;CDS=c.2219T>C;AA=p.I740T;CNT=1
7 55242463 COSM18420 AAGG A . . GENE=EGFR;STRAND=+;CDS=c.2234_2236delAGG;AA=p.E746delE;CNT=2
7 55242463 COSM1190791 AAGGAATTAAGAGAAG A . . GENE=EGFR;STRAND=+;CDS=c.2234_2248del15;AA=p.K745_A750>T;CNT=4
7 55242464 COSM13549 AGGAATTAAGAGAAGCAA AAG . . GENE=EGFR;STRAND=+;CDS=c.2235_2251>AG;AA=p.E746_T751>A;CNT=1
7 55242464 COSM255152 A AAACTCCCGTCGCTATCAA . . GENE=EGFR;STRAND=+;CDS=c.2234_2235ins18;AA=p.K745_E746insTPVAIK;CNT=1
7 55242464 COSM13550 AGGAATTAAGAGAAG AAATTC . . GENE=EGFR;STRAND=+;CDS=c.2235_2248>AATTC;AA=p.E746_A750>IP;CNT=3
7 55242464 COSM24869 AGGAATTAAGAGAAGCAAC A . . GENE=EGFR;STRAND=+;CDS=c.2235_2252del18;AA=p.E746_T751delELREAT;CNT=1
7 55242464 COSM6223 AGGAATTAAGAGAAGC A . . GENE=EGFR;STRAND=+;CDS=c.2235_2249del15;AA=p.E746_A750delELREA;CNT=1039
7 55242464 COSM51504 A AAATTCCCGTCGCTATCAA . . GENE=EGFR;STRAND=+;CDS=c.2234_2235ins18;AA=p.K745_E746insIPVAIK;CNT=6

Regards,
Palak Sheth

**Comment by palakpsheth** [comment]
Hi Zach,

Thank you for the prompt response. Your proposed solution would be extremely acceptable especially for reference database-type data from which the GT is usually unknown. An alternative would be assume ploid=1 if no GT field is found.

Thank you very much and keep up the great work!!

**Comment by zstephens** [comment]
Hey Palak,

I updated the VCF parsing as discussed.

One other thing I noticed about the example variants you sent is that many of them seem to overlap, either in position or in effect (i.e. deleted regions that overlap). genReads will ignore variants that coincide with the effect of a previously inserted variant, so I anticipate that only a subset of the specified variants will be inserted into the simulated data.

Thanks!
Zach

**Comment by palakpsheth** [comment]
Hi Zach,

Thats great! I will give it a try and get back to you. Also thank you for
the additional information about the overlapping variants. I will loop thru
the VCF one variant at a time to generate those mutant specific reads.

Thanks again!
