### ISSUE TITLE
Masked reference genome Error

### ISSUE THREAD

**Issue by afzm** [zstephens/neat-genreads#38]
When I try to simulate reads for the masked version of A.thaliana genome, after some progress, I experience the following error:

Error: weight or value vector given to DiscreteDistribution() are 0-length.

Data set:
ftp://ftp.ensemblgenomes.org/pub/plants/release-39/fasta/arabidopsis_thaliana/dna/Arabidopsis_thaliana.TAIR10.dna_rm.toplevel.fa.gz

Parameters:
-R 101 --pe 300 30 -c 20 --vcf --bam

It does not happen with the unmasked version.

**Comment by zstephens** [comment]
Greetings,

The issue stems from the fact that the masked reference contains many spans of non-N characters that are of insufficient length to sample reads from with the specified length and fragment-size distribution.

The region in particular that NEAT is failing on here is a section of the reference that is 337 bp long, and its attempts to compute positions where it could sample reads from this sequence with fragment lengths longer than that is causing the crash.

The easiest solution would be to skip reference regions that are smaller than the largest possible fragment length (in this case, 480, (300 + 6*30)), giving you no reads covering such regions.

An alternate solution would be to only allow reads with appropriately small fragment lengths to be sampled at these regions, which would give you coverage, but would perhaps be unrealistic with respect to the expected distribution of fragment sizes.

A third solution could be to use the unmasked reference, but supply a bed file (via the -t parameter) containing only the unmasked regions. This would result in NEAT sampling reads from all the unmasked regions as expected, but with a little bit of bleed over into the masked regions. See this image as an example: https://github.com/zstephens/neat-genreads/blob/master/docs/PE_SE_reads.png

Which of these solutions would be preferable for your application?

**Comment by afzm** [comment]
Thank you for the answer, in my opinion the first solution would be the most preferable

**Comment by zstephens** [comment]
I went ahead and implemented this (the first solution). The good news is that the simulation should no longer crash when it runs into these situations. However, when I was taking a look at the masked reference, I realized I should comment on how NEAT currently handles small patches of Ns. For example:

```
TCTAACGAATTCGTTAACNNNNNNNNNNGGTGAATTACGAATTCGTTAACTTGGCATAGA
TTAATGTTCCCACAACCTGTNNNNNNNNNNNNNNNNNNNNNNNNNTTTCTTCNNNNNNNG
ATTCCACAGCACAGTATGTAAATTTCGTTTTGTCCGGCAAATTTGGCCTTTACCATAANN
NNNNNCACCGCCTTCAGTGCCGTAGACAAATCAAAGCTCAAAAATAATTACGGAGTTTTA
AATTATTTCAAATGCTATAGTAAAGTTGTAANNNNNNNNNNNNNNNNCAATTAAACTCCC
TTAACCCCATAAGACAAGNNNNNNNATTAGTGGTTTTACTGAAAAAATGATTATTGGTGT
TATGTAAATGATAATATATTAAGGAAAATTTTTAGAACTTTTATTATATATTATCGTAAT
ATACGACTCGAATTTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
GGTTGTGAATTCTATCACGACAAGTCATATATATTACAAATATCATTTTCTGTTAAGGTT
AACAGAAAATTCTAAGTTGCGGTCTATTTGTCTTTTAAATCAAACACGAATGAGAAATTG
CCACTCATTTACTAATATTATATTGCGTATTCTTTGCAGATTATGTCTCTTTATAATCAT
CTTGCAAATTGACCCTTAATTTTAACATGTGGGTGGTNNNNNNNNNNCTAAAAGAAGAAA
CATTACTATTTCCATTGATAAGATTGATCGCAATCTATCTAGATTGAACTTGACAAAACT
TTTGTGATACGNNNNNNNNNNNNNNNNNNNNNNNNNGAGTTGGTATTGCTATCTGAGTTC
```

Regions like this are nigh impossible to sample reads from, because of this, the default behavior for NEAT is to "fill-in" small patches of Ns with random characters (where small is defined as regions smaller than the mean fragment length). This is usually a non-problem in unmasked reference assemblies (where at most we'd be randomly generating nucleotides for a few reference positions), but for references like this it quickly becomes unrealistic. Simulated reads will contain large amounts of non-reference content.

I'm leaning towards making this a user-input option (tentatively via -n), such that "-n random" would correspond to the current default behavior of randomly imputing ACGT characters into short stretches of Ns, and "-n ignore" would omit them altogether (resulting in a majority of the reference likely being unsampled because it is too broken up by spurious patches of Ns).

-Zach

**Comment by afzm** [comment]
It worked perfectly! Thank you
