### ISSUE TITLE
Pep8 and python standards

### ISSUE THREAD

**Issue by muppetjones** [zstephens/neat-genreads#5]
For the most part the code not too difficult to follow, but readability could be improved by limiting the line length to 80 columns and using better whitespace. I would recommend using a linter and following pep8 standards.

This is less an issue and more of a suggestion. Whether or not these recommendations are implemented is, of course, entirely up to you. Either way, thank you for taking the time to write this software!

For example, line `58` in `probability.py`:

```python
# current
return str(self.weights)+' '+str(self.values)+' '+self.method

# better
return str(self.weights) + ' ' + str(self.values) + ' ' + self.method

# best
return '{} {} {}'.format(self.weights, self.values, self.method)

# another option
return ' '.join([self.weights, self.values, self.method])
```

Similarly, lines `22-24` in `probability.py`:
```python
if len(self.values) != len(self.weights):
	print '\nError: length and weights and values vectors must be the same.\n'
	exit(1)
```
could be more pythonic by using exceptions:
```python
if len(self.values) != len(self.weights):
    msg = 'Length and weight vectors must be the same length'
    raise ValueError(msg)
```
(also, take a look at the `logging` package instead of using `print`).

Finally, tabs. I personally prefer using spaces (pep8 also recommends spaces), but the decision is ultimately yours; however, please try to be consistent. For example, lines `98-101` in `SequenceContainer.py` are indented using tabs up to the normal indentation, but the arguments are aligned to the `[` using spaces.

**Comment by zstephens** [comment]
Thank you for the style notes. I had chosen tabs as a personal preference (in that I just found them more attractive to work with), but I’ll look for inconsistencies like the one you noticed.

I’ll make a pass at adding some readability/usability improvements as you noted as well.

Thanks!
Zach


On Oct 11, 2016, at 5:08 PM, Stephen J Bush <notifications@github.com<mailto:notifications@github.com>> wrote:


For the most part the code not too difficult to follow, but readability could be improved by limiting the line length to 80 columns and using better whitespace. I would recommend using a linter and following pep8 standards.

This is less an issue and more of a suggestion. Whether or not these recommendations are implemented is, of course, entirely up to you. Either way, thank you for taking the time to write this software!

For example, line 58 in probability.py:

# current
return str(self.weights)+' '+str(self.values)+' '+self.method

# better
return str(self.weights) + ' ' + str(self.values) + ' ' + self.method

# best
return '{} {} {}'.format(self.weights, self.values, self.method)

# another option
return ' '.join([self.weights, self.values, self.method])

Similarly, lines 22-24 in probability.py:

if len(self.values) != len(self.weights):
    print '\nError: length and weights and values vectors must be the same.\n'
    exit(1)

could be more pythonic by using exceptions:

if len(self.values) != len(self.weights):
    msg = 'Length and weight vectors must be the same length'
    raise ValueError(msg)

(also, take a look at the logging package instead of using print).

Finally, tabs. I personally prefer using spaces (pep8 also recommends spaces), but the decision is ultimately yours; however, please try to be consistent. For example, lines 98-101 in SequenceContainer.py are indented using tabs up to the normal indentation, but the arguments are aligned to the [ using spaces.

**Comment by muppetjones** [comment]
Again, super quick response! Thanks!

Also--I hope you weren't offended by the comments/suggestions. Just things I noticed tracking down the other bug. Meant to be helpful.
