### ISSUE TITLE
Coverage and VAF

### ISSUE THREAD

**Issue by muppetjones** [zstephens/neat-genreads#6]
I'm trying to simulate normal and tumor samples with high levels of coverage, but the coverage is much lower than the given value.

### Normal

I generated samples with the below command, which resulted in two 6.2G FASTQ files, one 5.2G BAM file, and an empty VCF file.

```shell
for i in $(seq 1 100)
do
  ( python /neat-genreads/genReads.py \
	-r /refs/ensembl/ensembl_build_75.fa \
	-R 126 \
	-o /data/neat/normal \
	--pe 300 30 \
	-t /data/regions.bed \
	-c 100 \
	-M 0 \
	--bam --vcf \
	--job $i 100 ) &
done
wait
python /neat-genreads/mergeJobs.py \
	-i /data/neat/normal -o /data/neat/normal_merged -s /bin/samtools
```

Calling `samtools bedcov` with the region file showed that several thousand reads were aligning within each 2-7Mbp region, and `samtools mpileup` showed that the bam was averaging about 17 reads per bp (for a specified region).

```shell
# bedcov
...
1	XXX	YYY	2885
1	XXX	YYY	11359
1	XXX	YYY	3256
...

# mpileup (within region with 11359 reads)
...
1	XXX	N	16	NNNN	NNNN
1	XXX	N	16	NNNN	NNNN
1	XXX	N	18	NNNN	NNNN
1	XXX	N	18	NNNN	NNNN
1	XXX	N	17	NNNN	NNNN
...
```

### Tumor

Similarly, I tried to generate a synthetic tumor file with the following:

```shell
for i in $(seq 1 80)
do
  ( python /neat-genreads/genReads.py \
	-r /refs/ensembl/ensembl_build_75.fa \
	-R 126 \
	-o /data/neat/tumor \
	--pe 300 30 \
	-t /data/regions.bed \
	-c 80 \
	-M 0 \
	--bam --vcf \
	--job $i 100 ) &
done

for i in $(seq 81 100)
do
  ( python /neat-genreads/genReads.py \
	-r /refs/ensembl/ensembl_build_75.fa \
	-R 126 \
	-o /data/neat/tumor \
	--pe 300 30 \
	-t /data/regions.bed \
	-c 20 \
	-M 0 \
	--bam --vcf \
	-v /refs/cosmic/cosmic.vcf.gz \
	--job $i 100 ) &
done
wait
python /neat-genreads/mergeJobs.py \
	-i /data/neat/tumor -o /data/neat/tumor_merged -s /bin/samtools
```

This resulted in two 11G FASTQ, one 9.3G BAM, and another empty VCF. The subsequent `bedcov` and `mpileup` showed better coverage:

```shell
# bedcov
1	XXX	YYY	4887
1	XXX	YYY	20249
1	XXX	YYY	7470

# mpileup (for 20249)
1	XXX	N	25	
1	XXX	N	25	
1	XXX	N	27	
1	XXX	N	27	
1	XXX	N	27
```

I jumped up the coverage to `-c 1000` (still using `100` jobs), and (not unexpectedly) bash killed the jobs.

### Questions

1. Is this a valid way to simulate a mixed tumor / normal sample?
2. Why was the file size of the tumor sample 2x the normal despite the same coverage parameter?
3. Any thoughts on how to increase the coverage?

**Comment by muppetjones** [comment]
If I understand the code correctly, mutations from a given VCF file are added to a the same, single chromosome to simulate heterozygosity. Thus, generating a tumor sample as done above (80x w/o a VCF file, 20x w/), should result in a sample with a variant allele fraction (VAF) of `.10`.

Also, it seems to me that running the program multiple times at `-c 100` and combining the output would be another way to get the coverage I want.

Do I understand how NEAT is working?

**Comment by zstephens** [comment]
Hi there!

That’s not how I’d go about tumor/normal sample generation. Admittedly, some of the input options for NEAT are a little bit obtuse, I’ll explain coverage and job-splitting in a little more detail, I’ll start with the --job parameter:


The way NEAT generates data in parallel is by identifying independent reference regions (separated either by chromosome boundary, or by a large block of Ns) and sampling reads from a subset of those windows (as determined by the job number and total number of jobs). I.e. if we had a reference that looked like:

>chr1
ACGTACGTACGT … NNNNNNNNNNNNNN … ACGTACGTACGT

[--job 1 2] would fully process the first regions, and [--job 2 2] would fully process the second region. From your usage it seems like you were using the job command as though it affected coverage, which isn’t the case, unfortunately. So in order to generate a mixed tumor/normal dataset (with 20% of the reads containing mutations corresponding to the tumor dataset) I would do the following:


for N in [1,2,…,36]:
python genReads.py -r ref.fa -R 126 --pe 300 30 -c 80 -M 0 --bam --job N 36 -o output_normal
python genReads.py -r ref.fa -R 126 --pe 300 30 -c 20 -M 0 --bam --job N 36 -o output_tumor -v mutations.vcf --vcf


The complication now comes to merging all the files into a single dataset. We could use mergeJobs.py to create output_normal_merged* and outPut_tumor_merged* (by running it on both sets of data), then the user could manually merged the two sets into a single set. I acknowledge that this is cumbersome, and thus I have just updated the repository with an update to mergeJobs.py that allows merging multiple datasets (via multiple inputs with the -i parameter). The new usage would be as follows:


python mergeJobs.py -i /path/to/output_normal /path/to/output_tumor -o output_tumorNormalMerged -s /path/to/samtools


here’s some example console output from when I was testing this:

zach$ ls -lh /Users/zach/Desktop/tumorTest/
total 5712
-rw-r--r--  1 zach  staff   186K Oct 14 14:11 output_normal_golden.bam.job1of2
-rw-r--r--  1 zach  staff   397K Oct 14 14:11 output_normal_golden.bam.job2of2
-rw-r--r--  1 zach  staff   848B Oct 14 13:04 output_normal_golden.vcf.job1of2
-rw-r--r--  1 zach  staff     0B Oct 14 13:03 output_normal_golden.vcf.job2of2
-rw-r--r--  1 zach  staff   280K Oct 14 14:11 output_normal_read1.fq.job1of2
-rw-r--r--  1 zach  staff   554K Oct 14 14:11 output_normal_read1.fq.job2of2
-rw-r--r--  1 zach  staff   280K Oct 14 14:11 output_normal_read2.fq.job1of2
-rw-r--r--  1 zach  staff   554K Oct 14 14:11 output_normal_read2.fq.job2of2
-rw-r--r--  1 zach  staff    48K Oct 14 14:11 output_tumor_golden.bam.job1of2
-rw-r--r--  1 zach  staff   101K Oct 14 14:11 output_tumor_golden.bam.job2of2
-rw-r--r--  1 zach  staff   2.8K Oct 14 14:11 output_tumor_golden.vcf.job1of2
-rw-r--r--  1 zach  staff   3.2K Oct 14 14:11 output_tumor_golden.vcf.job2of2
-rw-r--r--  1 zach  staff    70K Oct 14 14:11 output_tumor_read1.fq.job1of2
-rw-r--r--  1 zach  staff   138K Oct 14 14:11 output_tumor_read1.fq.job2of2
-rw-r--r--  1 zach  staff    70K Oct 14 14:11 output_tumor_read2.fq.job1of2
-rw-r--r--  1 zach  staff   138K Oct 14 14:11 output_tumor_read2.fq.job2of2

zach$ mkdir /Users/zach/Desktop/tumorTest/merged/

zach$ python mergeJobs.py -i /Users/zach/Desktop/tumorTest/output_normal /Users/zach/Desktop/tumorTest/output_tumor -o /Users/zach/Desktop/tumorTest/merged/output_tumorNormalMerged -s /Users/zach/Desktop/bioinformatics/tools/samtools
cat /Users/zach/Desktop/tumorTest/output_normal_read1.fq.job1of2 /Users/zach/Desktop/tumorTest/output_normal_read1.fq.job2of2 /Users/zach/Desktop/tumorTest/output_tumor_read1.fq.job1of2 /Users/zach/Desktop/tumorTest/output_tumor_read1.fq.job2of2 > /Users/zach/Desktop/tumorTest/merged/output_tumorNormalMerged_read1.fq
cat /Users/zach/Desktop/tumorTest/output_normal_read2.fq.job1of2 /Users/zach/Desktop/tumorTest/output_normal_read2.fq.job2of2 /Users/zach/Desktop/tumorTest/output_tumor_read2.fq.job1of2 /Users/zach/Desktop/tumorTest/output_tumor_read2.fq.job2of2 > /Users/zach/Desktop/tumorTest/merged/output_tumorNormalMerged_read2.fq
/Users/zach/Desktop/bioinformatics/tools/samtools cat -h /Users/zach/Desktop/tumorTest/merged/output_tumorNormalMerged_golden.bam.tempHeader.sam /Users/zach/Desktop/tumorTest/output_normal_golden.bam.job1of2 /Users/zach/Desktop/tumorTest/output_normal_golden.bam.job2of2 /Users/zach/Desktop/tumorTest/output_tumor_golden.bam.job1of2 /Users/zach/Desktop/tumorTest/output_tumor_golden.bam.job2of2 > /Users/zach/Desktop/tumorTest/merged/output_tumorNormalMerged_golden.bam
cat /Users/zach/Desktop/tumorTest/output_normal_golden.vcf.job1of2 /Users/zach/Desktop/tumorTest/output_tumor_golden.vcf.job1of2_temp0 /Users/zach/Desktop/tumorTest/output_tumor_golden.vcf.job2of2 > /Users/zach/Desktop/tumorTest/merged/output_tumorNormalMerged_golden.vcf

zach$ ls -lh /Users/zach/Desktop/tumorTest/merged/
total 5664
-rw-r--r--  1 zach  staff   732K Oct 14 14:15 output_tumorNormalMerged_golden.bam
-rw-r--r--  1 zach  staff   6.1K Oct 14 14:15 output_tumorNormalMerged_golden.vcf
-rw-r--r--  1 zach  staff   1.0M Oct 14 14:15 output_tumorNormalMerged_read1.fq
-rw-r--r--  1 zach  staff   1.0M Oct 14 14:15 output_tumorNormalMerged_read2.fq

I also attached a pileup screenshot that verifies the presence of mutations with variant allele fraction 20% (homozygous in the 20% coverage data), and 10% (heterozygous in the 20% coverage data).

I hope this helps! This email got a lot more involved than I anticipated, I’ll address your coverage questions in another message.

Cheers,
Zach

[cid:8069AE69-C57B-46AC-93FC-DB9D7D78C9A5]


On Oct 12, 2016, at 12:23 PM, Stephen J Bush <notifications@github.com<mailto:notifications@github.com>> wrote:


If I understand the code correctly, mutations from a given VCF file are added to a the same, single chromosome to simulate heterozygosity. Thus, generating a tumor sample as done above (80x w/o a VCF file, 20x w/), should result in a sample with a variant allele fraction (VAF) of .10.

Also, it seems to me that running the program multiple times at -c 100 and combining the output would be another way to get the coverage I want.

Do I understand how NEAT is working?

**Comment by muppetjones** [comment]
Thanks for the info and the fix.

I might recommend doing the following for the `-i` argument, though:

```python
parser.add_argument(
    '-i', type=str, metavar='<str>',
    required=True, 
    action='append',
    help="* input prefix: [prefix_1] [prefix_2] ...")
```

which would change the usage to:
```
python mergeJobs.py -i <prefix_1> -i <prefix_2> -o <output_prefix> -s /path/to/samtools
```
